"""init

Revision ID: 2aa061da23b1
Revises: b1ff2f6820be
Create Date: 2024-11-13 16:30:42.404525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa061da23b1'
down_revision: Union[str, None] = 'b1ff2f6820be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    op.drop_index('ix_items_desc', table_name='items')
    op.create_index(op.f('ix_items_description'), 'items', ['description'], unique=False)
    op.drop_column('items', 'desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('desc', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_items_description'), table_name='items')
    op.create_index('ix_items_desc', 'items', ['desc'], unique=False)
    op.drop_column('items', 'description')
    # ### end Alembic commands ###
