"""init

Revision ID: b1ff2f6820be
Revises: 3c7af6d608b8
Create Date: 2024-11-13 16:25:36.887479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ff2f6820be'
down_revision: Union[str, None] = '3c7af6d608b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('desc', sa.String(), nullable=True))
    op.drop_index('ix_items_description', table_name='items')
    op.create_index(op.f('ix_items_desc'), 'items', ['desc'], unique=False)
    op.drop_column('items', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_items_desc'), table_name='items')
    op.create_index('ix_items_description', 'items', ['description'], unique=False)
    op.drop_column('items', 'desc')
    # ### end Alembic commands ###
